version: '3.3'

services:
    db:
      restart: always
      image: postgres:latest
      container_name: meli-database
      expose:
          - 5431
      ports:
          - 5431:5431
      environment:
          - POSTGRES_DB=meli
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=docker
      volumes:
          - ./scripts/sql:/docker-entrypoint-initdb.d
    app:
      build:
        dockerfile: Dockerfile
        context: .
      expose:
        - 80
      ports:
          - 80:80
        
      
